
services:

  _defaults:
    autowire: true      # Automatically injects dependencies in your services.

  Hr\ApiBundle\Repository\UserRepository:
    tags: ['doctrine.repository_service']

  # alias for cache interface
  Psr\Cache\CacheItemPoolInterface: '@Hr\ApiBundle\Service\CacheManager\RedisCache'

  Hr\ApiBundle\Security\ApiKeyAuthenticator:
    public: true
  Hr\ApiBundle\Security\ApiKeyGenerator:
    public: true
  Hr\ApiBundle\Security\ApiKeyUserProvider:
    public: true
  Hr\ApiBundle\Service\CacheManager\RedisCache:
    public: true
  Hr\ApiBundle\Service\JsonHelper:
    public: true
